Add files via upload
desfarik/it-academy-FD1-191-22 pull request #41
Opened 2022-06-19 20:44 UTC by divibell

a.shcherbich_homework2

2022-06-20 09:46 UTC, desfarik commented on task3.html
> +    <div class="border1">
Это все же немного не то. Иконки font-awesome вставляются +- также, как и из материала (ну или их можно скачать и юзать из локальной папки). SVG, в целом, тоже хорошо.

2022-06-20 09:50 UTC, desfarik commented on task3.html
> +        <div style="text-align: center">
Можно было немного больше поиграть и паддингами/маржинами, чтобы центрировать иконки.

2022-06-20 09:51 UTC, desfarik reviewed
А в свою папку кто будет файлы пихать?

2022-06-20 09:52 UTC, desfarik requested changes
Папка!

2022-06-21 16:30 UTC, closed without merging

2022-06-21 16:30 UTC, divibell commented
see https://github.com/desfarik/it-academy-FD1-191-22/pull/46/files